import {
  renderLoginPage,
  handleLogin,
  handleLogout,
  renderDashboard,
  getLiveStats,
  deletePermanent,
  deleteHistoryOnly,
  runSyncCheck,
  purgeBrokenFiles,
  updateConfig,
  toggleMaintenance,
  revokeSession,
  revokeAllSessions,
  searchFiles,
  previewBulkCleanup,
  executeBulkCleanup,
  clearDeletedHistory,
  getDeletedFiles,
  getAiRecommendations,
  generateRecommendations,
  updateAiConfig,
  listAiModels,
  testAiConnection,
  getNotificationsAction,
  logNotificationAction,
  markNotificationReadAction,
  clearNotificationsAction,
} from '../admin-actions';

export { generateRecommendations };

export const adminController = {
  renderLoginPage,
  handleLogin,
  handleLogout,
  renderDashboard,
  getLiveStats,
  deletePermanent,
  deleteHistoryOnly,
  runSyncCheck,
  purgeBrokenFiles,
  updateConfig,
  toggleMaintenance,
  revokeSession,
  revokeAllSessions,
  searchFiles,
  previewBulkCleanup,
  executeBulkCleanup,
  clearDeletedHistory,
  getDeletedFiles,
  getAiRecommendations,
  updateAiConfig,
  listAiModels,
  testAiConnection,
  getNotifications: getNotificationsAction,
  logNotification: logNotificationAction,
  markNotificationRead: markNotificationReadAction,
  clearNotifications: clearNotificationsAction,
};
