import {
  renderLoginPage,
  handleLogin,
  handleLogout,
  renderDashboard,
  getLiveStats,
  deletePermanent,
  deleteHistoryOnly,
  runSyncCheck,
  purgeBrokenFiles,
  updateConfig,
  toggleMaintenance,
  revokeSession,
  revokeAllSessions,
  searchFiles,
  previewBulkCleanup,
  executeBulkCleanup,
  clearDeletedHistory,
  getDeletedFiles,
  getAiRecommendations,
  generateRecommendations,
} from '../admin-actions';

export { generateRecommendations };

export const adminController = {
  renderLoginPage,
  handleLogin,
  handleLogout,
  renderDashboard,
  getLiveStats,
  deletePermanent,
  deleteHistoryOnly,
  runSyncCheck,
  purgeBrokenFiles,
  updateConfig,
  toggleMaintenance,
  revokeSession,
  revokeAllSessions,
  searchFiles,
  previewBulkCleanup,
  executeBulkCleanup,
  clearDeletedHistory,
  getDeletedFiles,
  getAiRecommendations,
};
